spring:
  application:
    name: ai-agent-backend
  jackson:
    deserialization:
      fail-on-unknown-properties: false

  ai:
    openai:
      api-key: "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"
      base-url: https://api.groq.com/openai/v1
      chat:
        model: openai/gpt-oss-120b
        extra-body:                                                                                                                    
                include_reasoning: false 
        # temperature: 0.5

server:
  port: 8082

weatherstack:
  access-key: 3588ddfccae2530c28d16c345180ad17
  base-url: http://api.weatherstack.com

rapidapi:
  booking:
    key: b435ea064emsh01eade17adad664p1b474bjsnb6c8610ea71f
    host: booking-com.p.rapidapi.com
    base-url: https://booking-com.p.rapidapi.com

# Actuator & Prometheus Exposure
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,prometheus,metrics
#   endpoint:
#     health:
#       show-details: always
#   metrics:
#     tags:
#       application: chatbot-monitoring

# Logging configuration
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG